common_params:
  GeoRegion: &GR
    region: EUR
    agr: EUR
    # use full data without land, border, and altitude masks
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2024
    period: WAS
    # ref period from-to (inclusive)
    ref_period: 1961-1990
    # cc period from-to (inclusive)
    cc_period: 2010-2024
  dataset: &DATA
    dataset: ERA5
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/
    statpath: &statpath /home/wegnet/results/static/
    maskpath: *statpath
    mask_sub: masks/
    result_path: &result_path /home/wegnet/results/TEA_indicators_test/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: *result_path
  recalc_threshold: false
  recalc_daily: false
  hourly: false
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true

create_region_masks:
  <<: *GR
  <<: *PATHS
  <<: *DATA
  <<: *PARAM
  <<: *TIME
  gr_type: polygon
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_orography.nc
  lsmfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_LSM.nc
