common_params:
  GeoRegion: &GR
    region: FBR
  parameter: &PARAM
    parameter: P24h_7to7
    precip: true
    threshold: 95
    threshold_type: perc
    unit: mm
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2024
    period: WAS
    ref_period: 1961-1990
    cc_period: 2010-2024
  dataset: &DATA
    dataset: ERA5Land
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5Land/
    statpath: /home/wegnet/results/TEA_indicators_test/static/
    maskpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/
    mask_sub: masks/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: /home/wegnet/results/TEA_indicators_test/
  recalc_threshold: false
  recalc_daily: true
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true

create_region_masks:
  <<: *GR
  <<: *PATHS
  <<: *DATA
  <<: *PARAM
  <<: *TIME
  # use UTM33N for SPARTACUS, because it has been regridded to WEGN grid
  target_sys: 32633
  gr_type: polygon
