common_params:
  GeoRegion: &GR
    region: SEA
    # use full data without land, border, and altitude masks
    gr_type: polygon
    sw_corner: null
    ne_corner: null
    center: null
    we_len: null
    ns_len: null
  parameter: &PARAM
    parameter: P24h_7to7
    precip: true
    threshold: 95
    threshold_type: perc
    unit: mm
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2024
    period: WAS
    # ref period from-to (inclusive)
    ref_period: 1961-1990
    # cc period from-to (inclusive)
    cc_period: 2008-2024
  dataset: &DATA
    dataset: SPARTACUS
  paths: &PATHS
    statpath: &statpath /home/wegnet/results/static/
    maskpath: *statpath
    mask_sub: masks/
    tmppath: /home/wegnet/results/TEA_indicators/tmp/

regrid_SPARTACUS_to_WEGNext:
  <<: *PARAM
  parameter: RR
  input_data_path: /data/reloclim/backup/ZAMG_SPARTACUS/data/v202402_v2.1/
  orography: false
  orofile: /data/reloclim/backup/ZAMG_INCA/data/original/INCA_orog_corrected_y_dim.nc
  wegnfile: /var/wegnet/netcdf/WEA/WN_L2_DD_v7_UTM_TF1_UTC_2020-08.nc
  outpath: /home/wegnet/tmp/

create_region_masks:
  <<: *GR
  <<: *DATA
  <<: *PATHS
  <<: *TIME
  subreg: false
  shpfile: /data/reloclim/backup/GEO/shapefiles/OEKS15/good/AUSTRIA.shp
  testfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_1961.nc
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_orography.nc
  lsmfile: /data/arsclisys/backup/clim-hydro/TEA-Indicators/ERA5/ERA5_LSM.nc
  outpath: /home/wegnet/tmp/

create_static_files:
  <<: *GR
  <<: *TIME
  <<: *PARAM
  <<: *DATA
  <<: *PATHS
  smoothing: 7
  input_data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/SPARTACUS/
  outpath: /home/wegnet/results/TEA_indicators/static/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  input_data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/SPARTACUS/
  outpath: /home/wegnet/results/TEA_indicators/
  recalc_daily: true
  decadal: true
  spreads: false
  decadal_only: false
  recalc_decadal: true
  compare_to_ref: false