common_params:
  input_data: &DATA
    dataset: HistAlp
  GeoRegion: &GR
    station: Graz
  parameters: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1877
    end: 2024
    period: annual
    # ref period from-to (inclusive)
    ref_period: 1961-1990
    # cc period from-to (inclusive)
    cc_period: 2010-2024
  paths: &PATHS
    input_data_path: /data/users/hst/cdrDPS/station_data/
    outpath: /home/wegnet/results/TEA_indicators/station_indices/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  recalc_daily: true
  hourly: false
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true
