common_params:
  input_data: &DATA
    dataset: ERA5
  GeoRegion: &GR
    region: full
  parameters: &PARAM
    parameter: Tx
    threshold: 28
    threshold_type: abs
    low_extreme: false
    unit: degC
  time_params: &TIME
    start: 1956
    end: 2024
    period: WAS
    # ref period from-to [from, to] (including both years)
    ref_period: 1961-1990
    # cc period from-to [from, to] (including both years)
    cc_period: 2008-2024
  paths: &PATHS
    input_data_path: $script_path/data/examples/ERA5_Tx_1956-2024_CH.nc
    outpath: $script_path/data/examples/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  recalc_daily: true
  decadal: true
  decadal_only: false
  spreads: true
  recalc_decadal: true
