common_params:
  GeoRegion: &GR
    station: Graz
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1877
    end: 2024
    period: annual
    # ref period from-to (inclusive)
    ref_period: 1961-1990
    # cc period from-to (inclusive)
    cc_period: 2010-2024
  dataset: &DATA
    dataset: HistAlp
  paths: &PATHS
    data_path: /data/users/hst/cdrDPS/station_data/
    result_path: &result_path /home/wegnet/results/TEA_indicators/station_indices/

calc_TEA: &calc_TEA
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: *result_path
  recalc_daily: true
  hourly: false
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true
